/*
Auto generated by shader_lib_gen.py
*/
#include <GL/glew.h>
#include "shaderlib.h"



void CVoxShader::LocateUniforms(){
    this->LocateUniform("MVP", this->MVP);
    this->LocateUniform("MV", this->MV);
}

void CVoxShader::Load(){
    CShader::Load("./shader/vox.vs", "./shader/vox.fs", "./shader/vox.gs");
}

// global shader objects
namespace shaderlib {
    VoxShader vox_shader = nullptr;
}

void shaderlib::loadshaders(){

    vox_shader = VoxShader(new CVoxShader);
    vox_shader -> Load();
    vox_shader -> LocateUniforms();

}
